trigger:
  - master
variables:
  - group: UiPath

stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: Azure-UIP
      steps:
      - task: UiPathPack@3
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          orchestratorConnection: 'zohan-lab'
          outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: UiPathDeploy@3
        inputs:
          orchestratorConnection: 'zohan-lab'
          packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
          folderName: 'Shared'
  - stage: TestDEV
    displayName:  Test After Publish
    dependsOn: DeployDEV
    condition: succeeded()
    jobs:
      - job: TestDEV
        pool: LAPTOP-Q338O4FK
        steps:
          - task: UiPathTest@3
            inputs:
              testTarget: 'TestSet'
              orchestratorConnection: 'UiPATH RPABOTSWORLD'
              testSet: 'UiPathAzureDevOps_Tests'
              folderName: 'Shared'
  
          


  