trigger:
  - master

variables:
  - group: UiPath

stages:
  - stage: Build
    displayName: Build Package
    jobs:
      - job: BuildPackage
        pool:
          name: Azure-UIP
        steps:
          - task: UiPathPack@3
            inputs:
              versionType: 'AutoVersion'
              projectJsonPath: '$(Build.SourcesDirectory)/project.json'
              orchestratorConnection: 'zohan-lab'
              outputPath: '$(Build.ArtifactStagingDirectory)/Output'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
          - task: UiPathDeploy@3
            inputs:
              orchestratorConnection: 'zohan-lab'
              packagesPath: '$(Build.ArtifactStagingDirectory)/Output'
              folderName: 'Shared'
  - stage: TestDEV
    displayName: Test After Publish
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: TestDEV
        pool:
          name: Azure-UIP
          steps:
          - suite: Addition Tests
          - test_case: Test addition of two numbers
            inputs:
              - x: 2
              - y: 3
            expected_output: 5
            steps:
              - add x and y
              - verify the result is equal to the expected output
          - test_case: Test addition of negative numbers
            inputs:
              - x: -2
              - y: -3
            expected_output: -5
            steps:
              - add x and y
              - verify the result is equal to the expected output
          - test_case: Test addition with decimal numbers
            inputs:
              - x: 1.5
              - y: 2.5
            expected_output: 4
            steps:
              - add x and y
              - verify the result is equal to the expected output
          - test_case: Test addition with large numbers
            inputs:
              - x: 1000000000000000000000000
              - y: 2000000000000000000000000
            expected_output: 3000000000000000000000000
            steps:
              - add x and y
              - verify the result is equal to the expected output
