trigger:
- main

pool:
  name: Azure-UIP

variables:
  group: UiPath
  devOrchestrator: 'https://dev.uipath.com/'
  tstOrchestrator: 'https://tst.uipath.com/'
  prdOrchestrator: 'https://prd.uipath.com/'
  projectJsonPath: "$(Build.SourcesDirectory)/project.json"
  outputPath: "$(Build.ArtifactStagingDirectory)/Output"
  orchestratorUrl: "$(devOrchestrator)"
  robotEnvironment: "Development"
  folderName: "Shared"
  orchestratorConnection: "Azure-UIpath"
  artifactName: "drop"

stages:
- stage: Build
  displayName: 'Create build artifact'
  jobs:
  - job: BuildArtifact
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(projectJsonPath)'
        orchestratorConnection: '$(orchestratorConnection)'
        outputPath: '$(outputPath)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputPath)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'

- stage: Asset
  displayName: 'Create assets'
  jobs:
  - job: CreateAssets
    steps:
    - task: UiPathAssets@3
      inputs:
        orchestratorConnection: '$(orchestratorConnection)'
        folderName: '$(folderName)'
        assetActionType: 'Deploy'
        csvFile: '$(Build.SourcesDirectory)/Data/Assets.csv'

- stage: TstDeploy
  displayName: 'Deploy to TST Orchestrator'
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: 'Run tests'
    steps:
    - task: UiPathTest@3
      inputs:
        testTarget: 'TestProject'
        orchestratorConnection: 'Azure-UIpath'
        folderName: 'Shared'
