trigger:
- master

stages:
- stage: Build
  displayName: Create build artifact
  jobs:
  - job: BuildArtifact
    pool:
      Azure-UIP
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)\project.json'
        orchestratorConnection: 'Azure-UIpath'
        outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: UiPathTest@3
      inputs:
        testTarget: 'TestProject'
        orchestratorConnection: 'Azure-UIpath'
        folderName: 'Shared'
