trigger:
- master

variables:
- group: UiPath

stages:
- stage: Build
  displayName: Build Package
  jobs:
  - job: BuildPackage
    pool: Azure-UIP
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)\project.json'
        orchestratorConnection: 'zohan-lab'
        outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- stage: Assest
  displayName: Create Assests
  jobs:
  - job: CreateAssests
    pool: Azure-UIP
    steps:
    - task: UiPathAssets@3
      inputs:
        orchestratorConnection: 'zohan-lab'
        folderName: 'Shared'
        assetActionType: 'Deploy'
        csvFile: '$(Build.SourcesDirectory)\Data\Assets.csv'

- stage: DeployDEV
  displayName: Deploy build artifact to DEV
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: deployDEV
    displayName: Deploy package to DEV Orchestrator
    pool: Azure-UIP
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UiPathPack@3
            inputs:
              versionType: 'AutoVersion'
              projectJsonPath: '$(Build.SourcesDirectory)\project.json'
              outputPath: '$(Build.ArtifactStagingDirectory)\Output'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'



- stage: TestDEV
  displayName: Test After Publish
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: TestDEV
  pool:
    name: Azure-UIP
    steps:
    - task: ApacheJMeter@1
    displayName: 'Aggression Test'
    inputs:
      testFiles: '**/*.csv, **/*.json, **/*.xml'  # Run on all CSV, JSON, and XML files in the repo
      jmeterHome: '/path/to/jmeter'  # Set the path to your JMeter installation
      propertiesJtl: 'results.jtl'  # Save results to a file named 'results.jtl'
      propertiesOverride: '-Jusers=50 -Jrampup=10'  # Set parameters for the test

