trigger:
  - master
variables:
  - group: UiPath

stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: Azure-UIP
      steps:
      - task: UiPathPack@3
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'zohan-lab'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop

  - stage: Assest
    displayName: Create Assests
    jobs:
      - job: CreateAssests
        pool: Azure-UIP
        steps:
        - task: UiPathAssets@3
          inputs:
            orchestratorConnection: 'zohan-lab'
            folderName: 'Shared'
            assetActionType: 'Deploy'
            csvFile: '$(Build.SourcesDirectory)\Data\Assets.csv'
  
          


  - stage: TestDEV
    displayName:  Test After Publish
    dependsOn: DeployDEV
    condition: succeeded()
    jobs:
      - job: TestDEV
        pool: Azure-UIP
        steps:
          - task: UiPathTest@3
            inputs:
              testTarget: 'TestProject'
              orchestratorConnection: 'zohan-lab'
              folderName: 'Shared'