trigger:
- main

variables:
- group: UiPath

stages:
- stage: Build
  displayName: Build Package
  jobs:
  - job: BuildPackage
    pool: Azure-UIP
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)\project.json'
        outputType: 'Process'
        orchestratorConnection: 'Azure-UIpath'
        outputPath: '$(Build.ArtifactStagingDirectory)'
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Assest
  displayName: Create Assets
  jobs:
  - job: CreateAssets
    pool: Azure-UIP
    steps:
    - task: UiPathAssets@3
      inputs:
        orchestratorConnection: 'Azure-UIpath'
        folderName: 'Shared'
        assetActionType: 'Deploy'
        csvFile: '$(Build.SourcesDirectory)\Data\Assets.csv'

- stage: DeployDEV
  displayName: Deploy build artifact to DEV
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: deployDEV
    displayName: Deploy package to DEV Orchestrator
    pool: Azure-UIP
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UiPathDeploy@3
            inputs:
              orchestratorConnection: 'Azure-UIpath'
              packagesPath: '$(Pipeline.Workspace)\drop\'
              folderName: 'Shared'

- stage: CodeQuality
  displayName: Check Code Analysis
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: CodeQuality
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Sonar'
        organization: 'rpabotsworld'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'rpabotsworld_UiPathAzureDevOpsExample'
        cliProjectName: 'UiPathAzureDevOpsExample'
        cliSources: '.'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: TestDEV
  displayName: Test After Publish
  dependsOn: DeployDEV
  condition: succeeded()
  jobs:
  - job: TestDEV
    pool: Azure-UIP
    steps:
    - task: UiPathTest@3
      inputs:
        testTarget: 'TestSet'
        orchestratorConnection: 'UiPATH RPABOTSWORLD'
        testSet: 'UiPathAzureDevOps_Tests'
        folderName: 'Shared'
        testReportDestination: '$(Pipeline.Workspace)\drop\'
