trigger:
- main

stages:
- stage: Build
  displayName: Create build artifact
  jobs:
  - job: BuildArtifact
    pool:
      Azure-UIP
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)\project.json'
        orchestratorConnection: 'Azure-UIpath'
        outputPath: '$(Build.ArtifactStagingDirectory)\Output'
