trigger:
- main

variables:
  group: UiPath
  devOrchestrator: 'https://dev.uipath.com/'
  tstOrchestrator: 'https://tst.uipath.com/'
  prdOrchestrator: 'https://prd.uipath.com/'

stages:
- stage: Build
  displayName: 'Create build artifact'
  jobs:
  - job: BuildArtifact
    pool:
      name: Azure-UIP
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)/project.json'
        orchestratorConnection: 'Azure-UIpath'
        outputPath: '$(Build.ArtifactStagingDirectory)/Output'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DevDeploy
  displayName: 'Deploy to DEV Orchestrator'
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    pool:
      name: Azure-UIP
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)/project.json'
        orchestratorConnection: 'Azure-UIpath'
        outputPath: '$(Build.ArtifactStagingDirectory)/Output'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: UiPathDeploy@3
      inputs:
        orchestratorConnection: 'Azure-UIpath'
        packagesPath: '$(Build.ArtifactStagingDirectory)/Output'
        folderName: 'Shared'
        orchestratorUrl: '$(devOrchestrator)'
        robotEnvironment: 'Development'

- stage: TstDeploy
  displayName: 'Deploy to TST Orchestrator'
  dependsOn: DevDeploy
  jobs:
  - job: TstDeployJob
    pool:
      name: Azure-UIP
    steps:
      # steps for deploying the UiPath project to TST
    
  - job: SmokeTestJob
    pool:
      name: Azure-UIP
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          cd $(Build.SourcesDirectory)
          php artisan test --testsuite=Smoke
      env:
        APP_ENV: 'testing'
        DB_CONNECTION: 'sqlite'

- stage: PrdDeploy
  displayName: 'Deploy to PRD Orchestrator'
  dependsOn: TstDeploy
  jobs:
  - job: PrdDeployJob
    pool:
      name: Azure-UIP
    steps:
    - task: UiPathPack@3
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)/project.json'
        orchestratorConnection: 'Azure-UIpath'
        outputPath: '$(Build.ArtifactStagingDirectory)/Output'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: UiPathDeploy@3
      inputs:
        orchestratorConnection: 'Azure-UIpath'
        packagesPath: '$(Build.ArtifactStagingDirectory)/Output'
        folderName: 'Shared'
        orchestratorUrl: '$(prdOrchestrator)'
        robotEnvironment: 'Production'
