trigger:
  - master
variables:
  - group: UiPath

stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool:  Azure-UIP
      steps:
      - task: UiPathPack@3
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'Azure-UIpath'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop