trigger:
  - main

stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: Azure-UIP
      cancelTimeoutInMinutes: 
- task: UiPathPack@3
    inputs:
      versionType: 'AutoVersion'
      projectJsonPath: '$(Build.SourcesDirectory)\project.json'
      orchestratorConnection: 'Azure-UIpath'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'